# Generated by Django 5.0.6 on 2024-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicetenants_devicestatistics_devicelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatistics',
            name='downtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicestatistics',
            name='uptime',
            field=models.IntegerField(default=0),
        ),
    ]
